using PowerBI_MCP.DTO;
using Microsoft.AspNetCore.Mvc;
using PowerBI_MCP.Interfaces;
using ModelContextProtocol.Server;
using System.ComponentModel;

namespace PowerBI_MCP.MCP
{
    [ApiController]
    [Route("api/[controller]/[action]")]
    [McpServerToolType]
    public class QueryController
    {
        private readonly IDaxService _daxService;

        public QueryController(IDaxService daxService)
        {
            _daxService = daxService;
        }

        [McpServerTool]
        [Description("Runs a DAX query on a specified model via MCP.")]
        public object Mcp_RunDaxQuery(
            [Description("DAX query text to execute")] string query,
            [Description("Name of the model on which to execute the query")] string modelName)
        {
            try
            {
                var result = _daxService.RunDaxQuery(query, modelName);
                return new
                {
                    success = true,
                    message = $"Query executed successfully on model '{modelName}'.",
                    modelName = modelName,
                    query = query,
                    result = result
                };
            }
            catch (Exception ex)
            {
                return new
                {
                    success = false,
                    message = $"Error running DAX query: {ex.Message}",
                    error = ex.Message
                };
            }
        }

        [McpServerTool]
        [Description("Runs an MDX query on a specified model via MCP.")]
        public object Mcp_RunMdxQuery(
            [Description("MDX query text to execute")] string query,
            [Description("Name of the model on which to execute the query")] string modelName)
        {
            try
            {
                var result = _daxService.RunMdxQuery(query, modelName);
                return new
                {
                    success = true,
                    message = $"Query executed successfully on model '{modelName}'.",
                    modelName = modelName,
                    query = query,
                    result = result
                };
            }
            catch (Exception ex)
            {
                return new
                {
                    success = false,
                    message = $"Error running MDX query: {ex.Message}",
                    error = ex.Message
                };
            }
        }

        [McpServerTool]
        [Description(
            "Saves a DAX query generated by the MCP (AI) client. " +
            "The MCP client will generate both the DAX query text and a file name, " +
            "then call this tool to persist the query to the designated storage location."
        )]
        public object Mcp_SaveDaxQuery(
            [Description("The file name generated by the MCP client for saving the DAX query")] string queryName,
            [Description("The DAX query generated by the MCP client that will be saved")] string query)
        {
            try
            {
                var result = _daxService.SaveDaxQuery(queryName, query);
                return new
                {
                    success = true,
                    message = $"Successfully saved AI-generated DAX query '{queryName}'.",
                    queryName = queryName,
                    query = query,
                    result = result
                };
            }
            catch (Exception ex)
            {
                return new
                {
                    success = false,
                    message = $"Error saving DAX query: {ex.Message}",
                    error = ex.Message
                };
            }
        }
    }
}
